[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tetra"
dynamic = ["version"]
description = "Full stack component framework for Django using Alpine.js"
authors = [
    { name = "Sam Willis", email="samw@hey.com"},
    { name = "Christian González", email = "christian.gonzalez@nerdocs.at" }
]
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["python", "django", "framework", "components"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "cryptography>=37.0.1",
    "Django>=3.2.0",
    "python-dateutil>=2.8.2",
]


[project.urls]
Homepage = "https://tetraframework.com"
Documentation = "https://tetraframework.readthedocs.io"
Repository = "https://github.com/tetra-framework/tetra"


[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
    "pre-commit",
    "black",
    #"gunicorn==20.1.0",
    "markdown>=3.3.7",
    "python-dateutil>=2.8.2",
    "PyYAML>=6.0",
    "sourcetypes>=0.0.4",
]


[tool.setuptools.dynamic]
version = {attr = "tetra.__version__"}

[tool.setuptools.packages.find]
exclude = ["docs", "tests", "demosite"]
