name: pytest-django CI

on:
  push:
    # TODO: change that to "main" when merging
    branches: [ "tetra-package" ]
  pull_request:
    branches: [ "tetra-package" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        cd tests
        npm install
    - name: Run Tests
      run: |
        cd tests
        pytest